### ISSUE TITLE
instacrash with `fluid.datasetquery~`

### ISSUE THREAD

**Issue by rconstanzo** [flucoma/flucoma-max#320] opened 2022-08-05 12:25 UTC
Having a hard time reproducing it, but I do have a crash report. Basically I was building up a query for `fluid.datasetquery~` and got an instacrash when sending this message:
`clear, filter 44 > 2000., addrange 0 44, transform coll dump`

I can supply the dataset/patch if desired, but as mentioned I'm having a hard time reproducing it.

Pretty sure I'm on the latest/release (version 1.0.0+sha.d0e42a3.core.sha.f86443a).

Crash report attached but crashed thread starts with:
```
Thread 0 Crashed:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   org.flucoma.fluid.libmanipulation	0x0000000128182615 fluid::algorithm::DataSetQuery::process(fluid::FluidDataSet<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, double, 1l> const&, fluid::FluidDataSet<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, double, 1l>&, fluid::FluidDataSet<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, double, 1l>&) + 677
```

[crash.zip](https://github.com/flucoma/flucoma-max/files/9268535/crash.zip)

**Comment by weefuzzy** [comment] 2022-08-22 09:51
Yeah, if you can send sample data, that would be good. Nothing much else to go on otherwise.

**Comment by rconstanzo** [comment] 2022-08-22 19:24
I don't know what exact data I was using when I got this crash, but these are the types of data that it would have been.

[Archive.zip](https://github.com/flucoma/flucoma-max/files/9397031/Archive.zip)

(at the time I don't know if I was using `transformjoin` yet to use one dataset to query another, but in any case, the `data dataset.json` is identical in structure to what I would have used when I got this crash.

**Comment by tremblap** [comment] 2024-10-11 16:11
ok I cannot reproduce with the dataset you sent in SC. This is an extreme example doing 100000 times in SC:

```
a = FluidDataSet(s).read("/Users/pa/Downloads/Archive/query datatset.json").print
b = FluidDataSet(s)
c = FluidDataSetQuery(s)

c.clear.filter(2, ">", -20).addRange(0, 3).transform(a,b)
a.print
b.print

// run 100000 times
fork{var cond = Condition.new; 100000.do{c.clear.filter(2, ">", -20).addRange(0, 3).transform(a,b,{cond.unhang; \done.postln});cond.hang}}
```
No hang. Again a memory issue? Let me know if you can reproduce.

**Comment by rconstanzo** [comment] 2024-10-11 16:19
Not had any issues with `fluid.datasetquery~` in some time (as far as I remember). Back then I basically wrapped all the terminology and plumbing in a wrapper and haven't thought about it since.

**Comment by tremblap** [comment] 2024-10-11 16:23
oh ok. should we close it and open a new one when we can reproduce?

**Comment by rconstanzo** [comment] 2024-10-11 16:25
Totally.

IMO any of these "it crashed once but I can't reproduce" bugs from 2 years ago can probably all be closed unless there's something else it's pointing towards. If I would have had the same crash again I would have posted about it anyways.

**Comment by tremblap** [comment] 2024-10-11 16:34
be my guest :) I'll do this one. If you happen to have 1h of headspace, if you could look at your old reports and confirm those that are still alive it gives me more time to investigate under the hood <3

**Closed by tremblap** 2024-10-11 16:34 UTC
